# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' OLS with estimated knots
#' This is a function about how to calculate the OLS estimator with given knots.
#' @param Y a vector being the observations of the response variable
#' @param X a matrix with the first column being the variable of interest and the left column being the covariates 
#' @param tau_iter a vector being the estimated knots 
#' @return estimate of the coefficients and response variable
#' @examples
#' library(lsknots)
#' set.seed(12345)
#' n = 1000
#' eta = 0.5 
#' sig = 0.03
#' a=  rnorm(n,0,1)
#' Z = rnorm(n,0,2) 
#' u = (a+Z)/sqrt(5)
#' X= pnorm(u,mean=0,sd=1) 
#' e = rnorm (n,0,sd=sig)  
#' Y = theta[1] + theta[2]*X + theta[3] * as.numeric(X > theta[7]) * ( X - theta[7] ) + theta[4] * as.numeric(X > theta[8]) * ( X - theta[8] ) + theta[5] * as.numeric(X > theta[9]) * ( X - theta[9] )  + theta[6] * as.numeric(X > theta[10]) * ( X - theta[10] )+ eta*Z+ e 
#' A=matrix(c(X,Z),ncol=2)
#' tau00=c(0.3,0.5,0.85,0.95)
#' yhat =knots_ols(Y,A,tau0)$y_hat
#' betahat=knots_ols(Y,A,tau0)$beta_hat
knots_ols <- function(Y, X, tau_iter) {
    .Call(`_lsknots_knots_ols`, Y, X, tau_iter)
}

#' updated NR methods to find knots
#' This is a function about how to find knots in spline linear regression
#' @param Y a vector being the observations of the response variable
#' @param X a matrix with the first column being the variable of interest and the left column being the covariates 
#' @param tau_iter a vector being the estimated knots
#' @param epsilon threshold for error 
#' @examples
#' library(lsknots)
#' set.seed(12345)
#' n = 1000
#' eta = 0.5 
#' sig = 0.03
#' a=  rnorm(n,0,1)
#' Z = rnorm(n,0,2) # Z: confounder/other covariate
#' u = (a+Z)/sqrt(5)
#' X= pnorm(u,mean=0,sd=1) #X: factor of interest with change-point effects: uniform (0,1)
#' e = rnorm (n,0,sd=sig)  #e: error term
#' Y = theta[1] + theta[2]*X + theta[3] * as.numeric(X > theta[7]) * ( X - theta[7] ) + theta[4] * as.numeric(X > theta[8]) * ( X - theta[8] ) + theta[5] * as.numeric(X > theta[9]) * ( X - theta[9] )  + theta[6] * as.numeric(X > theta[10]) * ( X - theta[10] )+ eta*Z+ e 
#' tau00=c(0.3,0.5,0.85,0.95)
#' A=matrix(c(X,Z),ncol=2)
#' knots_find(Y,A,tau00)
knots_find <- function(Y, X, tau_iter, epsilon = 0.000001) {
    .Call(`_lsknots_knots_find`, Y, X, tau_iter, epsilon)
}

#' function to find the estimated standard deviation for knots
#' This is a function about how to find the estimated standard deviation for knots in spline linear regression
#' @param y a vector being the observations of the response variable
#' @param X a vec being the variable of interest
#' @param Z a matrix being the covariates 
#' @param tau_out a vector being the estimated knots
#' @return sd_out a vector being the estimated standard deviation for knots
#' @examples
#' library(lsknots)
#' set.seed(12345)
#' n = 1000
#' eta = 0.5 
#' sig = 0.03
#' a=  rnorm(n,0,1)
#' Z = rnorm(n,0,2) # Z: confounder/other covariate
#' u = (a+Z)/sqrt(5)
#' X= pnorm(u,mean=0,sd=1) #X: factor of interest with change-point effects: uniform (0,1)
#' e = rnorm (n,0,sd=sig)  #e: error term
#' Y = theta[1] + theta[2]*X + theta[3] * as.numeric(X > theta[7]) * ( X - theta[7] ) + theta[4] * as.numeric(X > theta[8]) * ( X - theta[8] ) + theta[5] * as.numeric(X > theta[9]) * ( X - theta[9] )  + theta[6] * as.numeric(X > theta[10]) * ( X - theta[10] )+ eta*Z+ e 
#' tau_out = knots_find(Y,A,tau00)
#' sdout = knots_sd(Y, X, as.matrix(Z),tau_out)
knots_sd <- function(y, X, Z, tau_out) {
    .Call(`_lsknots_knots_sd`, y, X, Z, tau_out)
}

interval <- function(quantile, tau_out, sd_out) {
    .Call(`_lsknots_interval`, quantile, tau_out, sd_out)
}

